### ISSUE TITLE
Script is producing Error

### ISSUE THREAD

**Issue by huettenwirt** [Stannieman/audacity-with-asio-builder#1]
Hi,

I just wanted to compile my very own version of Audacity with ASIO, but the script came up with the following error:

ERROR: for audacity-asio-builder  Cannot start service audacity-asio-builder: CreateComputeSystem e6ea7ba42d9c6f14d3eff607c23b26ad903b8c5cfdf4c4d5d91219475bebf636: Die gebietsschemaspezifische Ressource für die gewünschte Meldung ist nicht vorhanden.

This error comes up twice and I have no clue what to do ;-)

Any advice?

I replaced the Hash with the most current Hash from the Audacity GitHub Repo. Anything else I left untouched...

Thanks,
Huettenwirt

**Comment by Stannieman** [comment]
Hi huettenwirt!

That's not supposed to happen indeed :( I will look into it this weekend.
For sure I'll also push a new image with newer tools.
Sorry for the inconvenience.

**Comment by Stannieman** [comment]
@huettenwirt it is working now locally. Will be for tomorrow, need to update readme etc and drinking beer now :)

**Comment by huettenwirt** [comment]
Beer is well deserved, I would say...

Am Sa., 26. Jan. 2019, 21:22 hat Stan Wijckmans <notifications@github.com>
geschrieben:

**Comment by Stannieman** [comment]
@huettenwirt image is currently pushing to Docker hub, it should work with that one + the whole process is a bit more robust.
You only need the BuildAudacity.ps1 script from now on, no docker-compose.
https://github.com/Stannieman/audacity-with-asio-builder/releases/tag/1.1.0
