### ISSUE TITLE
OS Build incompatibility

### ISSUE THREAD

**Issue by huettenwirt** [Stannieman/audacity-with-asio-builder#2]
Great Update, I was almost there, but 

after updating Windows 10 to 1803, I'm on build 10.17134.556 which is incompatible to the build you used:

Starting Docker container to build Audacity with ASIO support
Unable to find image 'stannieman/audacity-with-asio-builder:1.1.0' locally
1.1.0: Pulling from stannieman/audacity-with-asio-builder
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host.

Not sure how to get to the same build since I'm using the standard windows update and I'm located in Germany. Maybe I just need to wait for additional updates to get to the same build?

Cheers,
Huettenwirt

**Comment by Stannieman** [comment]
Yes you need the October update. Automatic rollout started 1 or 2 weeks ago but IIRC it goes in phases and might not have reached you yet. If you are willing to manually start the upgrade you can do so from here: https://www.microsoft.com/en-us/software-download/windows10

**Comment by Stannieman** [comment]
@huettenwirt did you try it already?

**Comment by huettenwirt** [comment]
The Update wasn't rolled out yet and I had no time to perform the manual update yet. But I will definitely give it a try since the standard latency between my Xenix QX1202USB Audio Interface and Audacity is way too high. Hoping to get some better results with this build. Did you experience any instability of your windows after installing the ASIO drivers?

**Comment by Stannieman** [comment]
I don't use it much actually, and not at all on my main machine :D But every now and then I do use it and I found it frustrating that you are supposed to be a programmer in order to do so. That's why I made this thing so it's a bit more accessible to the average user. No need to set a thousand tools, SDKs, variables etc.

**Comment by Stannieman** [comment]
You can also install a VM of course
