### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by bit-whisperer** [Stannieman/audacity-with-asio-builder#6]
PREPARING BUILD FOR PACKAGING
Get-ChildItem : Cannot find path 'C:\BuildDir\Audacity\win\Release' because it does not exist.
At C:\Build.ps1:73 char:1
+ Get-ChildItem BuildDir/Audacity/win/Release -Filter '*.lib' | Remove- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\Audacity\win\Release:String) [Get-ChildItem], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Remove-Item : Cannot find path 'C:\BuildDir\Audacity\win\Release\Audacity.exp' because it does not exist.
At C:\Build.ps1:74 char:1
+ Remove-Item BuildDir/Audacity/win/Release/Audacity.exp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\Aud...se\Audacity.exp:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\BuildDir\Audacity\win\Release\Audacity.iobj' because it does not exist.
At C:\Build.ps1:75 char:1
+ Remove-Item BuildDir/Audacity/win/Release/Audacity.iobj
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\Aud...e\Audacity.iobj:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\BuildDir\Audacity\win\Release\Audacity.ipdb' because it does not exist.
At C:\Build.ps1:76 char:1
+ Remove-Item BuildDir/Audacity/win/Release/Audacity.ipdb
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\Aud...e\Audacity.ipdb:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\BuildDir\Audacity\win\Release\Audacity.pdb' because it does not exist.
At C:\Build.ps1:77 char:1
+ Remove-Item BuildDir/Audacity/win/Release/Audacity.pdb
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\Aud...se\Audacity.pdb:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Copy-Item : The filename, directory name, or volume label syntax is incorrect.
At C:\Build.ps1:79 char:1
+ Copy-Item $vcRedistPath/* BuildDir/Audacity/win/Release/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxbase311u_net_vc_custom.dll' because it does not exist.
At C:\Build.ps1:81 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxbase$wxWidgetsVersionInFileName`u_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...t_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxbase311u_vc_custom.dll' because it does not exist.
At C:\Build.ps1:82 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxbase$wxWidgetsVersionInFileName`u_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...u_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxmsw311u_adv_vc_custom.dll' because it does not exist.
At C:\Build.ps1:83 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxmsw$wxWidgetsVersionInFileName`u_a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...v_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxmsw311u_core_vc_custom.dll' because it does not exist.
At C:\Build.ps1:84 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxmsw$wxWidgetsVersionInFileName`u_c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...e_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxmsw311u_html_vc_custom.dll' because it does not exist.
At C:\Build.ps1:85 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxmsw$wxWidgetsVersionInFileName`u_h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...l_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxbase311u_xml_vc_custom.dll' because it does not exist.
At C:\Build.ps1:86 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxbase$wxWidgetsVersionInFileName`u_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...l_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\BuildDir\WXWidgets\lib\vc_dll\wxmsw311u_qa_vc_custom.dll' because it does not exist.
At C:\Build.ps1:87 char:1
+ Copy-Item "$env:WXWIN/lib/vc_dll/wxmsw$wxWidgetsVersionInFileName`u_q ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildDir\WXW...a_vc_custom.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Rename-Item : Cannot rename because item at 'BuildDir/Audacity/win/Release' does not exist.
At C:\Build.ps1:88 char:1
+ Rename-Item BuildDir/Audacity/win/Release Audacity
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Rename-Item], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand

CREATING ZIP PACKAGING
Compress-Archive : The path 'BuildDir/Audacity/win/Audacity' either does not exist or is not a valid file system path.
At C:\Build.ps1:94 char:1
+ Compress-Archive BuildDir/Audacity/win/Audacity externalvolume/Audaci ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (BuildDir/Audacity/win/Audacity:String) [Compress-Archive], InvalidOper
   ationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Compress-Archive

**Comment by Stannieman** [comment]
For me it still works, so I really need more info:
- What Windows version are you using?
- What Audacity version are you building? Other than default?
- What wxWidgets version are you using? Other than default?
- What ASIO SDK version are you using? Other than default?
- Do you happen to have experimental Docker features enabled to run Linux and Windows containers simultaneously?

**Comment by stephanGarland** [comment]
Tagging on, as it doesn't build for me either, same errors.

Windows 10 Pro Build 18362.657
All options in script set to default
Not enabling Linux and Windows containers simultaneously

**Comment by Stannieman** [comment]
In the BuildAudacity.ps1 script on line 43 there is `--isolation $processIsolationPart`.
Can both of you try to change it to `--isolation hyperv`?

If you are on 1903 (18362) then the script detects this and runs the container in process isolation mode.
I've seen a problem last week where the production build agents at my work stopped working (probably after a Windows update) and setting them to hyperv isolation mode fixed the issue.
I suspect we see the same problem here.
Process isolation mode is faster when it works, but seems a bit sensitive to external factors sometimes.

**Comment by stephanGarland** [comment]
That fixed it! Thanks, you can close the issue.

**Comment by Stannieman** [comment]
> That fixed it! Thanks, you can close the issue.

No I will first remove this option from the script and release new version, THEN I will close the issue ;)

**Comment by Stannieman** [comment]
Ok 1.3.0 is out that always uses hyperv isolation. Also updated base image to 1909.
