### ISSUE TITLE
DNS Failure

### ISSUE THREAD

**Issue by Spartan-II-117** [Stannieman/audacity-with-asio-builder#7]
Hello, This container failed to resolve github.com until i provided a DNS server on my local network, causing the script to break all over the place. I resolved this for myself by adding the --DNS flag to my local DNS server

**Comment by Stannieman** [comment]
If you start a container from a fresh Windows Server Core image, can you ping github.com from there?
I've never seen this happen on my end and others also don't seem to have this issue, so looks more like something on your end.

**Comment by panabar** [comment]
I've also experienced what Spartan-II-117 wrote and adding --dns flag with my local DNS server fixed the issue. I'm using a PiHole server for DNS requests and all DHCP leases.
Also thank you for simplifying this daunting task.

**Comment by Stannieman** [comment]
@panabar can you try to ping from inside a clean Windows Server Core container?
I don't do anything related to networking so I think it's just some normal Docker/Windows containers behavior. Maybe I can add --dns in the script in the future if that's the case.

**Comment by panabar** [comment]
@Stannieman I can't ping google.com when I run a clean Windows Server Core container without --dns. 
Here is what I did:
`docker run -it mcr.microsoft.com/windows/servercore:1909 powershell`
then
`ping www.google.com`
`Ping request could not find host www.google.com. Please check the name and try again.`
Then I checked `ipconfig /all` inside the container:
`DNS Servers . . . . . . . . . . . : 172.26.112.1 10.14.10.13 10.14.10.254`
The first one is probably related to docker. The last two are probably related to my workplace, but I'm elsewhere on a WiFi connection. The 'DNS Servers' line outside the container is:
`DNS Servers . . . . . . . . . . . : 192.168.0.254`

**Comment by Stannieman** [comment]
I will fix a different issue this week and also take the opportunity to add --dns to the build script, then you should always be good.
I'll use 1.1.1.1 if no objections.

**Comment by Stannieman** [comment]
Fixed in latest version!
